### ISSUE TITLE
Failed to activate a package

### ISSUE THREAD

**Issue by mcmxc** [eerrecalde/bracket-matcher-highlight#3]
<img width="465" alt="screen shot 2016-12-08 at 06 40 48" src="https://cloud.githubusercontent.com/assets/17690047/20997791/5afb4e2c-bd11-11e6-87ce-5cc305a160d0.png">

an error occurs each time I start Atom editor. It all started up after last update.

**Comment by eerrecalde** [comment]
Apologise.
I've updated the package for an issue with tha new version of Atom 1.12.x (as you can see in your screenshot).
Will check how possible is it to keep both versións active and let you know.

**Comment by eerrecalde** [comment]
Assuming this is fixed by now? Just update Atom to any official version.
