### ISSUE TITLE
bracket-matcher-highlight doesn't start because of incompatible native module oniguruma

### ISSUE THREAD

**Issue by dhoffi** [eerrecalde/bracket-matcher-highlight#6]
bracket-matcher-highlight doesn't start on my mac anymore.
Developer Console says:

```
Failed to require the main module of 'bracket-matcher-highlight'
because it requires one or more incompatible native modules (oniguruma).
```

I have already had oniguruma installed via brew for other (non atom) dependencies. Might this cause problems?
Is there anyting I can try or do to solve this?

```
$ brew info oniguruma
oniguruma: stable 6.6.1 (bottled)
Regular expressions library
https://github.com/kkos/oniguruma/
/usr/local/Cellar/oniguruma/6.4.0 (17 files, 1.3MB)
  Poured from bottle on 2017-07-11 at 21:08:42
/usr/local/Cellar/oniguruma/6.5.0 (17 files, 1.3MB)
  Poured from bottle on 2017-08-12 at 11:24:11
/usr/local/Cellar/oniguruma/6.6.0 (17 files, 1.3MB)
  Poured from bottle on 2017-08-30 at 08:37:23
/usr/local/Cellar/oniguruma/6.6.1 (17 files, 1.3MB) *
  Poured from bottle on 2017-09-02 at 23:53:22
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/oniguruma.rb
```

already did several reinstalls and `apm rebuild` ... nothing worked so far

**Comment by eerrecalde** [comment]
Hey @dhoffi I'm sorry about the delay in coming back to you. 
If I do the same `brew info oniguruma` I get a "not installed" message. 

I'd say maybe try uninstalling it, and then reinstalling the bracket-matcher-highlight

Let me know how that goes,
Emiliano.

**Comment by eerrecalde** [comment]
A bit more about this.. I've just got the exact same message but it disappeared after rebuilding the package. This was atom asking me if I want to rebuild it to solve the issue. And it worked just fine.

**Comment by dhoffi** [comment]
well I totally removed atom
reinstalled atom
reinstalled all my packages
and still get the same error

*sigh*

```
atom --version
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

but on "incompatible Packages" Tab I get the following message ... maybe a better hint to what I could try to do?


bracket-matcher-highlight 0.5.0

oniguruma@6.2.1 – The module '/Users/hoffmd9/.atom/packages/bracket-matcher-highlight/node_modules/oniguruma/build/Release/onig_scanner.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 49. This version of Node.js requires NODE_MODULE_VERSION 53. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or`npm install`).

**Comment by dhoffi** [comment]
upgrading node apm itself and rebuilding `apm rebuild` did solve the problem:

```
npm i -g npm
```
